name: Pull Request Linting and Testing
run-name: Run Linting and Tests on Pull Request "${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-linting

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/run-tests
